services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=user'
      - 'POSTGRES_USER=fitiz-user'
      - 'POSTGRES_PASSWORD=fitiz-user'
    ports:
      - '5432:5432'


