apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stg

commonLabels:
  env: stg

resources:
  - ../../base
  - config.yaml
  - namespace.yaml

patchesStrategicMerge:
  - deployment.yaml
