apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

commonLabels:
  env: dev

resources:
  - ../../base
  - config.yaml
  - namespace.yaml

patchesStrategicMerge:
  - deployment.yaml
